import base from '@glint/config/eslint/base'

/** @type {import('eslint').Linter.Config[]} */
export default [
  ...base,
  {
    languageOptions: {
      parserOptions: {
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // Generated by orval from apps/api/openapi.json; never edited by hand
    ignores: ['src/generated/**'],
  },
]
